package ru.practicum.android.diploma.common.domain.models

data class Vacancy(
    val vacancyId: Int,
    val city: String,
    val jobDescription: String?,
    val jobTiming: String?,
    val experience: String?,
    val keySkills: List<String>?,
    val professionalRoles: List<String>?,
    val jobName: String,
    val currency: String,
    val from: String,
    val to: String,
    val schedule: String?,
    val employerId: Int,
    val employerEmail: String?,
    val employerContactName: String?,
    val employerPhone: List<String>?,
    val comment: String?,
    val employerLogoUrls90: String?,
    val employerLogoUrls240: String?,
    val employerLogoUrlsOriginal: String?,
    val employerName: String,
)
